#lang racket
(define (cylinder)
  (display "Вычисление объема цилиндра.")
  (newline)
  (display "Введите исходные данные:")
  (newline)
  (display "радиус основания (см) = ")
  (define r (read))
  (newline)
  (display "Высота цилиндра (см) = ")
  (define h (read))
  (newline)
  (display "Объем цилиндра = ")
  (display (* pi r r h))
  (display " куб.см.")
  (newline)
  (cylinder))
(cylinder)
